version: '3'

services:

  webapp:
    build: ./go
    volumes:
      - ./go:/go/src/webapp
    env_file:
      - ".env"
    environment:
      - "PAYMENT_API"
    links:
      - payment
      - memcached
    ports:
      - "127.0.0.1:8000:8000"
